var labels = {
  "salute": "Bienvenido! Estoy aquí para ayudarte con las gestiones sobre tu solicitud.",
  "init_choice":"¿En que puedo ayudarte?",
  "response_option1": "Para consultar el estado de su solicitud debe indicar el código del deudor.",
  "response_option2": "Para consultar el estado de su solicitud debe indicar el código del deudor.",
  "response_option3": "Puedes indicarnos el código de la solicitud?",
  "response_option4": "Para realizar una nueva solicitud debe de utilizar la app ó la web. Sí tiene algúna duda contacte con helpdesk. ",
  "response_option5": "Para ampliar cupo debe de contactar con suscriptor.",
  "response_option6": "Debe montar una petición nueva a la compañía, donde se tienen que añadir en las observaciónes el cambio de compañia y la compañia anterior. Se recomienda adjuntar información sobre el cambio.",
  "response_option7": "Se debe realizar la eliminación de la línea nóminada en la pagina y despues enviar al backoffice la solicitud de carga anónima o discrecional.",
  "no_found_res": "¡No se ha encontrado ninguna solicitud con el codigo del deudor introducido!",
  "many_policies": "Se han encontrado varias solicitudes con estos datos. ¿A qué póliza se refiere?",
  "only_one": "Existe una única póliza en función de su clasificación: ",
  "pending_state": "El estado de la póliza %1 es PENDIENTE/EN REVISION. ¿Quiere realizar alguna acción sobre esta solicitud?",
  "res_pending1": "¡Gracias, un saludo!",
  "res_pending2": "Su solicitud tiene un plazo de XX. Estamos trabajando en la solución de su solicitud. ¡Gracias, un saludo!",
  "res_pending3": "Póngase en contacto con su suscriptor. Su teléfono es 3333333 y su correo es: prueba@prueba.com",
  "complete_state_info":"La poliza numero: %1 tiene el estado %2. El valor aprobado es: %3",
  "complete_state": " El anexo se le enviara en breve a su correo. Si es urgente, también se puede descargar en nuestra app.",
  "finOk_info": "La poliza numero: %1 tiene el estado %2. La cobertura perdida es: %3 ,  debido a: %4.",
  "finOk": " ¡Gracias, un saludo!",
  "response1": "Puedes volver a revaluar con el respaldo de los socios, para esto deberás solicitar la revisión del cupo y adjuntar la siguiente información - Declaración de la renta ...",
  "response3": "Póngase en contacto con su suscriptor. Su teléfono es 3333333 y su correo es: prueba@prueba.com",
  "response2": "El estado se ha analizado con la última información enviada. Puede entregar información más actualizada, aunque no se garantiza la otorgación del cupo.",
  "response4": "Desafortunadamente no se podrá mejorar la cobertura. ¡Gracias!",
  "removed_state": "El estado de la poliza_uno es ELIMINADO. Alguien de su organización ha solicitado la eliminación de esta cobertura. ¿Le es suficiente esta información?",
  "request_removed1": "Deberá volver a solicitar la cobertura!",
  "request_removed": "Gracias, hasta pronto!",
  "nointent": " ¡No te he entendido! ¡Estoy aqui para ayudarte con la gestion de polizas!",
  "option1": "Estado de una solicitud",
  "option2": "Información sobre mi solicitud",
  "option3": "No me ha llegado el anexo de clasificación",
  "option4": "Solicitud nueva",
  "option5": "Ampliar cupo",
  "option6": "Modificaciones deudor",
  "option7": "Corregir tipo cobertura",
  "pending1": "Estoy de acuerdo con el estado",
  "pending2": "Solicitar evaluación urgente ",
  "pending3": "Solicitar despacho de forma urgente",
  "ask_debtor_cod": "Cual es tu codigo de deudor?",
  "ask_poliza_cod": "Cual es el codigo de su poliza?",
  "error_getPolicies": "¡Se ha producido un error, intentalo de nuevo!",
  "state_error": "El estado de su poliza no esta registrado.",
  "error_server": "No se ha podido realizar la consulta sobre sus polizas. Por favor, intentalo de nuevo mas tarde",
  "first_error_dialog": "La opción introducina no es valida!",
  "error_policy": "No existe ninguna poliza con el codigo seleccionado!",
  "choise_policy": "¡Elije la poliza para la cual quieres realizar la consulta!",
  "error_pending": "La opción incorrecta!",
  "info_police":"Para la poliza con el numero: %1 la fecha es: %2 el remitente es: %3",
  "annex_mess": " Pronto se enviara el anexo de clasificación. Si es urgente lo puede descargar de la página!",
  "error_response": "Se ha producido un error al leer la respuesta",
  "valid_code":"Código validado, le enviaremos el anexo en breve",
  "valid_code_error":"Código erroneo",
  "info_state_policy":"La poliza numero: %1 tiene el estado %2. El valor solicitado es: %3 y el valor concedido es de: %4,  debido a:  %5.",
  "info_state_question":"¿Es suficiente la información?",
  "login_info":"Para acceder al chatbot es necesario estar registrado",
  "login_question_user":"Introduce el usuario",
  "login_question_password":"Introduce la password para el usuario %1",
  "login_error":"Error al leer la respuesta del login",
  "login_ok":"El login es correcto",
  "other_query":"Quiere realizar otra consulta",
  "the_end_text":"Gracias y hasta pronto"
}
exports.labels = labels;